sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L1 Voltage"
    register_type: holding
    address: 644
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L2 Voltage"
    register_type: holding
    address: 645
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L3 Voltage"
    register_type: holding
    address: 646
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L1 Power"
    register_type: holding
    address: 650
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L2 Power"
    register_type: holding
    address: 651
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load L3 Power"
    register_type: holding
    address: 652
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load Power"
    register_type: holding
    address: 653
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load Frequency"
    register_type: holding
    address: 655
    unit_of_measurement: "Hz"
    device_class: frequency
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Daily Load Consumption"
    id: daily_load_consumption
    register_type: holding
    address: 526
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Total Consumption"
    id: total_consumption
    register_type: holding
    address: 527
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:home-lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load UPS L1 Power"
    register_type: holding
    address: 640
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load UPS L2 Power"
    register_type: holding
    address: 641
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load UPS L3 Power"
    register_type: holding
    address: 642
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Load UPS Power"
    register_type: holding
    address: 643
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:home-lightning-bolt"
    disabled_by_default: true

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "AC Load Relay Reserved"
    register_type: holding
    address: 552
    bitmask: 0x2
    icon: "mdi:toggle-switch-variant"
