sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV1 Power"
    id: pv1_power
    register_type: holding
    address: 672
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: U_WORD
    icon: "mdi:solar-power-variant"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV2 Power"
    id: pv2_power
    register_type: holding
    address: 673
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: U_WORD
    icon: "mdi:solar-power-variant"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV3 Power"
    id: pv3_power
    register_type: holding
    address: 674
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: U_WORD
    icon: "mdi:solar-power-variant"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV4 Power"
    id: pv4_power
    register_type: holding
    address: 675
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: U_WORD
    icon: "mdi:solar-power-variant"
    disabled_by_default: true

  - platform: template
    name: "PV Power"
    unit_of_measurement: "W"
    id: pv_power
    device_class: power
    accuracy_decimals: 0
    update_interval: 5s
    icon: "mdi:solar-power-variant"
    lambda: |-
      float pv1 = isnan(id(pv1_power).state) ? 0.0 : id(pv1_power).state;
      float pv2 = isnan(id(pv2_power).state) ? 0.0 : id(pv2_power).state;
      float pv3 = isnan(id(pv3_power).state) ? 0.0 : id(pv3_power).state;
      float pv4 = isnan(id(pv4_power).state) ? 0.0 : id(pv4_power).state;
      return pv1 + pv2 + pv3 + pv4;

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV1 Voltage"
    register_type: holding
    address: 676
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:solar-power-variant"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV1 Current"
    register_type: holding
    address: 677
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:solar-power-variant"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV2 Voltage"
    register_type: holding
    address: 678
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:solar-power-variant"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV2 Current"
    register_type: holding
    address: 679
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:solar-power-variant"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV3 Voltage"
    register_type: holding
    address: 680
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:solar-power-variant"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV3 Current"
    register_type: holding
    address: 681
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:solar-power-variant"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV4 Voltage"
    register_type: holding
    address: 682
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:solar-power-variant"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "PV4 Current"
    register_type: holding
    address: 683
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:solar-power-variant"
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Daily PV Production"
    id: daily_pv_production
    register_type: holding
    address: 529
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:solar-power"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Total PV Production"
    id: total_pv_production
    register_type: holding
    address: 534
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:solar-power"

switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "MPPT Multi-point Scanning"
    register_type: holding
    address: 341
    bitmask: 0x0004
    entity_category: config
    icon: "mdi:solar-power-variant-outline"
