name: Build CI

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master, develop]
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        file:
          - deye_hybrid_3p_lv
          - deye_hybrid_1p_lv
          - deye_hybrid_3p_hv

        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Copy test files to main directory
        run: |
          if [ -d "tests/" ]; then
            cp -r tests/* .
            echo "Copied files from tests/ to main directory"
          else
            echo "ERROR: tests/ directory not found"
            exit 1
          fi

      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}
